<?php

return [
    'countries' => [
        'Afghanistan' => 'AF',
        'Albania' => 'AL',
        'Algeria' => 'DZ',
        'American Samoa' => 'AS',
        'Andorra' => 'AD',
        'Angola' => 'AO',
        'Anguilla' => 'AI',
        'Antarctica' => 'AQ',
        'Antigua and Barbuda' => 'AG',
        'Argentina' => 'AR',
        'Armenia' => 'AM',
        'Aruba' => 'AW',
        'Australia' => 'AU',
        'Austria' => 'AT',
        'Azerbaijan' => 'AZ',
        'Bahamas' => 'BS',
        'Bahrain' => 'BH',
        'Bangladesh' => 'BD',
        'Barbados' => 'BB',
        'Belarus' => 'BY',
        'Belgium' => 'BE',
        'Belize' => 'BZ',
        'Benin' => 'BJ',
        'Bermuda' => 'BM',
        'Bhutan' => 'BT',
        'Bolivia' => 'BO',
        'Bosnia and Herzegovina' => 'BA',
        'Botswana' => 'BW',
        'Brazil' => 'BR',
        'Brunei' => 'BN',
        'Bulgaria' => 'BG',
        'Burkina Faso' => 'BF',
        'Burundi' => 'BI',
        'Cambodia' => 'KH',
        'Cameroon' => 'CM',
        'Canada' => 'CA',
        'Cape Verde' => 'CV',
        'Chad' => 'TD',
        'Chile' => 'CL',
        'China' => 'CN',
        'Colombia' => 'CO',
        'Comoros' => 'KM',
        'Congo' => 'CG',
        'Costa Rica' => 'CR',
        'Croatia' => 'HR',
        'Cuba' => 'CU',
        'Cyprus' => 'CY',
        'Czech Republic' => 'CZ',
        'Denmark' => 'DK',
        'Djibouti' => 'DJ',
        'Dominica' => 'DM',
        'Dominican Republic' => 'DO',
        'Ecuador' => 'EC',
        'Egypt' => 'EG',
        'El Salvador' => 'SV',
        'Equatorial Guinea' => 'GQ',
        'Eritrea' => 'ER',
        'Estonia' => 'EE',
        'Ethiopia' => 'ET',
        'Fiji' => 'FJ',
        'Finland' => 'FI',
        'France' => 'FR',
        'Germany' => 'DE',
        'Ghana' => 'GH',
        'Greece' => 'GR',
        'Greenland' => 'GL',
        'Guatemala' => 'GT',
        'Guinea' => 'GN',
        'Haiti' => 'HT',
        'Honduras' => 'HN',
        'Hungary' => 'HU',
        'Iceland' => 'IS',
        'India' => 'IN',
        'Indonesia' => 'ID',
        'Iran' => 'IR',
        'Iraq' => 'IQ',
        'Ireland' => 'IE',
        'Israel' => 'IL',
        'Italy' => 'IT',
        'Jamaica' => 'JM',
        'Japan' => 'JP',
        'Jordan' => 'JO',
        'Kazakhstan' => 'KZ',
        'Kenya' => 'KE',
        'Kuwait' => 'KW',
        'Latvia' => 'LV',
        'Lebanon' => 'LB',
        'Lesotho' => 'LS',
        'Liberia' => 'LR',
        'Libya' => 'LY',
        'Lithuania' => 'LT',
        'Luxembourg' => 'LU',
        'Madagascar' => 'MG',
        'Malawi' => 'MW',
        'Malaysia' => 'MY',
        'Maldives' => 'MV',
        'Mali' => 'ML',
        'Malta' => 'MT',
        'Mexico' => 'MX',
        'Monaco' => 'MC',
        'Mongolia' => 'MN',
        'Montenegro' => 'ME',
        'Morocco' => 'MA',
        'Mozambique' => 'MZ',
        'Myanmar' => 'MM',
        'Namibia' => 'NA',
        'Nepal' => 'NP',
        'Netherlands' => 'NL',
        'New Zealand' => 'NZ',
        'Nicaragua' => 'NI',
        'Niger' => 'NE',
        'Nigeria' => 'NG',
        'Norway' => 'NO',
        'Oman' => 'OM',
        'Pakistan' => 'PK',
        'Palestine' => 'PS',
        'Panama' => 'PA',
        'Papua New Guinea' => 'PG',
        'Paraguay' => 'PY',
        'Peru' => 'PE',
        'Philippines' => 'PH',
        'Poland' => 'PL',
        'Portugal' => 'PT',
        'Qatar' => 'QA',
        'Romania' => 'RO',
        'Russia' => 'RU',
        'Rwanda' => 'RW',
        'Saudi Arabia' => 'SA',
        'Senegal' => 'SN',
        'Serbia' => 'RS',
        'Seychelles' => 'SC',
        'Singapore' => 'SG',
        'Slovakia' => 'SK',
        'Slovenia' => 'SI',
        'Somalia' => 'SO',
        'South Africa' => 'ZA',
        'South Korea' => 'KR',
        'Spain' => 'ES',
        'Sri Lanka' => 'LK',
        'Sudan' => 'SD',
        'Sweden' => 'SE',
        'Switzerland' => 'CH',
        'Syria' => 'SY',
        'Taiwan' => 'TW',
        'Tajikistan' => 'TJ',
        'Tanzania' => 'TZ',
        'Thailand' => 'TH',
        'Togo' => 'TG',
        'Tonga' => 'TO',
        'Trinidad and Tobago' => 'TT',
        'Tunisia' => 'TN',
        'Turkey' => 'TR',
        'Uganda' => 'UG',
        'Ukraine' => 'UA',
        'United Arab Emirates' => 'AE',
        'United Kingdom' => 'GB',
        'United States' => 'US',
        'Uruguay' => 'UY',
        'Uzbekistan' => 'UZ',
        'Vanuatu' => 'VU',
        'Venezuela' => 'VE',
        'Vietnam' => 'VN',
        'Yemen' => 'YE',
        'Zambia' => 'ZM',
        'Zimbabwe' => 'ZW',
    ],
    // 'countries' => [
    //     'Afghanistan',
    //     'Albania',
    //     'Algeria',
    //     'American Samoa',
    //     'Andorra',
    //     'Angola',
    //     'Anguilla',
    //     'Antarctica',
    //     'Antigua and Barbuda',
    //     'Argentina',
    //     'Armenia',
    //     'Aruba',
    //     'Australia',
    //     'Austria',
    //     'Azerbaijan',
    //     'Bahamas',
    //     'Bahrain',
    //     'Bangladesh',
    //     'Barbados',
    //     'Belarus',
    //     'Belgium',
    //     'Belize',
    //     'Benin',
    //     'Bermuda',
    //     'Bhutan',
    //     'Bolivia',
    //     'Bosnia and Herzegovina',
    //     'Botswana',
    //     'Brazil',
    //     'Brunei',
    //     'Bulgaria',
    //     'Burkina Faso',
    //     'Burundi',
    //     'Cambodia',
    //     'Cameroon',
    //     'Canada',
    //     'Cape Verde',
    //     'Chad',
    //     'Chile',
    //     'China',
    //     'Colombia',
    //     'Comoros',
    //     'Congo',
    //     'Costa Rica',
    //     'Croatia',
    //     'Cuba',
    //     'Cyprus',
    //     'Czech Republic',
    //     'Denmark',
    //     'Djibouti',
    //     'Dominica',
    //     'Dominican Republic',
    //     'Ecuador',
    //     'Egypt',
    //     'El Salvador',
    //     'Equatorial Guinea',
    //     'Eritrea',
    //     'Estonia',
    //     'Ethiopia',
    //     'Fiji',
    //     'Finland',
    //     'France',
    //     'Germany',
    //     'Ghana',
    //     'Greece',
    //     'Greenland',
    //     'Guatemala',
    //     'Guinea',
    //     'Haiti',
    //     'Honduras',
    //     'Hungary',
    //     'Iceland',
    //     'India',
    //     'Indonesia',
    //     'Iran',
    //     'Iraq',
    //     'Ireland',
    //     'Israel',
    //     'Italy',
    //     'Jamaica',
    //     'Japan',
    //     'Jordan',
    //     'Kazakhstan',
    //     'Kenya',
    //     'Kuwait',
    //     'Latvia',
    //     'Lebanon',
    //     'Lesotho',
    //     'Liberia',
    //     'Libya',
    //     'Lithuania',
    //     'Luxembourg',
    //     'Madagascar',
    //     'Malawi',
    //     'Malaysia',
    //     'Maldives',
    //     'Mali',
    //     'Malta',
    //     'Mexico',
    //     'Monaco',
    //     'Mongolia',
    //     'Montenegro',
    //     'Morocco',
    //     'Mozambique',
    //     'Myanmar',
    //     'Namibia',
    //     'Nepal',
    //     'Netherlands',
    //     'New Zealand',
    //     'Nicaragua',
    //     'Niger',
    //     'Nigeria',
    //     'Norway',
    //     'Oman',
    //     'Pakistan',
    //     'Palestine',
    //     'Panama',
    //     'Papua New Guinea',
    //     'Paraguay',
    //     'Peru',
    //     'Philippines',
    //     'Poland',
    //     'Portugal',
    //     'Qatar',
    //     'Romania',
    //     'Russia',
    //     'Rwanda',
    //     'Saudi Arabia',
    //     'Senegal',
    //     'Serbia',
    //     'Seychelles',
    //     'Singapore',
    //     'Slovakia',
    //     'Slovenia',
    //     'Somalia',
    //     'South Africa',
    //     'South Korea',
    //     'Spain',
    //     'Sri Lanka',
    //     'Sudan',
    //     'Sweden',
    //     'Switzerland',
    //     'Syria',
    //     'Taiwan',
    //     'Tajikistan',
    //     'Tanzania',
    //     'Thailand',
    //     'Togo',
    //     'Tonga',
    //     'Trinidad and Tobago',
    //     'Tunisia',
    //     'Turkey',
    //     'Uganda',
    //     'Ukraine',
    //     'United Arab Emirates',
    //     'United Kingdom',
    //     'United States',
    //     'Uruguay',
    //     'Uzbekistan',
    //     'Vanuatu',
    //     'Venezuela',
    //     'Vietnam',
    //     'Yemen',
    //     'Zambia',
    //     'Zimbabwe',
    // ],

];
